<a href="https://colab.research.google.com/github/Hemanthk408/Apple-stock/blob/main/apple_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/Apple_stock_history.csv")
df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1980-12-12,0.100453,0.100890,0.100453,0.100453,469033600,0.0,0.0
1,1980-12-15,0.095649,0.095649,0.095213,0.095213,175884800,0.0,0.0
2,1980-12-16,0.088661,0.088661,0.088224,0.088224,105728000,0.0,0.0
3,1980-12-17,0.090408,0.090845,0.090408,0.090408,86441600,0.0,0.0
4,1980-12-18,0.093029,0.093466,0.093029,0.093029,73449600,0.0,0.0
...,...,...,...,...,...,...,...,...
10348,2021-12-28,180.160004,181.330002,178.529999,179.289993,79144300,0.0,0.0
10349,2021-12-29,179.330002,180.630005,178.139999,179.380005,62348900,0.0,0.0
10350,2021-12-30,179.470001,180.570007,178.089996,178.199997,59773000,0.0,0.0
10351,2021-12-31,178.089996,179.229996,177.259995,177.570007,64025500,0.0,0.0
10352,2022-01-03,177.830002,182.880005,177.710007,182.009995,104487900,0.0,0.0

In [5]:
df.isnull().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10353 entries, 0 to 10352
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          10353 non-null  object
 1   Open          10353 non-null  float64
 2   High          10353 non-null  float64
 3   Low           10353 non-null  float64
 4   Close         10353 non-null  float64
 5   Volume        10353 non-null  int64
 6   Dividends     10353 non-null  float64
 7   Stock Splits  10353 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 647.2+ KB

In [11]:
df["Date"]=pd.to_datetime(df["Date"],format="%Y-%m-%d")

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10353 entries, 0 to 10352
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          10353 non-null  datetime64[ns]
 1   Open          10353 non-null  float64
 2   High          10353 non-null  float64
 3   Low           10353 non-null  float64
 4   Close         10353 non-null  float64
 5   Volume        10353 non-null  int64
 6   Dividends     10353 non-null  float64
 7   Stock Splits  10353 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 647.2 KB

In [13]:
import plotly.express as px